'''
Django settings for care project.

Generated by 'django-admin startproject' using Django 2.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
'''

import os

from care import PROJECT_BASE_DIR

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = PROJECT_BASE_DIR

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['SECRET_KEY']

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'assg'                
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'care.middlewares.logging.LoggingMiddleware',
    'care.middlewares.handle_exception.HandleExceptionMiddleware',
    'care.middlewares.authentication.AuthenticationMiddleware',
    # 'care.middlewares.authorization.AuthorizationMiddleware',
    'care.middlewares.request_validation.RequestValidationMiddleware'
]

ROOT_URLCONF = 'care.urls'

WSGI_APPLICATION = 'care.wsgi.application'

CORS_ORIGIN_ALLOW_ALL = True

CORS_ALLOW_METHODS = (
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
)

# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASE_SETTINGS = {
    'mongodb': {
        'NAME': os.environ.get('MONGO_DB_NAME', 'Assignment'),
        'USER': os.environ.get('MONGO_DB_USER'),
        'PASS': os.environ.get('MONGO_DB_PASSWORD'),
        'HOST': os.environ.get('MONGO_DB_HOST', 'localhost'),
        'PORT': os.environ.get('MONGO_DB_PORT', '27017'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = os.environ.get('TIMEZONE', 'UTC')

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Authentication middleware settings
AUTHENTICATION_URL = os.environ['AUTHENTICATION_URL']

# Authorization middleware settings
AUTHORIZATION_URL = os.environ["AUTHORIZATION_URL"]
